name: ecommerce_demo
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.2
  intl: ^0.19.0
  equatable: ^2.0.5
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  iconsax: ^0.0.8
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.5
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  flutter_bloc: ^8.1.4
  flutter_native_splash: ^2.3.8
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.2.0

  go_router: ^13.2.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  firebase_authentication_repository:
    path: packages/firebase_auth_repository

  cupertino_icons: ^1.0.2
  firebase_app_check: ^0.2.1+14
  badges: ^3.1.2
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  custom_refresh_indicator: ^3.1.0
  google_sign_in: ^6.2.1
  flutter_dotenv: ^5.1.0
  hydrated_bloc: ^9.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/t-store-splash-logo-black.png"

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/errors/
    - assets/images/reviews/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/icons/snack_bar/
    - assets/images/on_boarding_images/
    - assets/.env

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 900
